from typing import List, Optional, Dict, Any
from sqlmodel import SQLModel, Field, Relationship, Column, JSON
import uuid

from .base import BaseModel

class PlanBase(SQLModel):
    """Base plan model with common fields."""
    total_price: float = Field(ge=0, nullable=False)
    score: Optional[float] = Field(default=None, ge=0, le=10)
    explanation: Optional[str] = Field(default=None)
    flight_data: Optional[Dict[str, Any]] = Field(default=None, sa_column=Column(JSON))
    hotel_data: Optional[Dict[str, Any]] = Field(default=None, sa_column=Column(JSON))
    car_data: Optional[Dict[str, Any]] = Field(default=None, sa_column=Column(JSON))
    attractions_data: Optional[Dict[str, Any]] = Field(default=None, sa_column=Column(JSON))
    deeplinks: Dict[str, Any] = Field(default={}, sa_column=Column(JSON))
    ai_generated: bool = Field(default=False, nullable=False)  # True if generated by AI, False if manual
    manual: bool = Field(default=False, nullable=False)  # True if manually created, False if AI-generated

class PlanCreate(PlanBase):
    """Model for creating a new plan."""
    chat_id: uuid.UUID

class PlanUpdate(SQLModel):
    """Model for updating plan information."""
    total_price: Optional[float] = Field(None, ge=0)
    score: Optional[float] = Field(None, ge=0, le=10)
    explanation: Optional[str] = None
    flight_data: Optional[Dict[str, Any]] = None
    hotel_data: Optional[Dict[str, Any]] = None
    car_data: Optional[Dict[str, Any]] = None
    attractions_data: Optional[Dict[str, Any]] = None
    deeplinks: Optional[Dict[str, Any]] = None
    ai_generated: Optional[bool] = None
    manual: Optional[bool] = None

class Plan(PlanBase, BaseModel, table=True):
    """Plan model for database representation."""
    __tablename__ = "plans"
    
    chat_id: uuid.UUID = Field(foreign_key="chats.id", nullable=False)
    
    # Relationships
    chat: "Chat" = Relationship(back_populates="plans")

